### ISSUE TITLE
part 数组有demo吗

### ISSUE THREAD

**Issue by rebeccalifei** [ikidou/Retrofit2Demo#3]
part 数组有demo吗

**Comment by ikidou** [comment]
```java
@POST("/partTest")
@Multipart
partTest(@Part MultipartBody.Part[] parts);
```
就这样定义就行了，需要注意的有两点
- Part 注解不能有值。Part的值只在使用 参数类型为RequestBody时，才需要值。
- 数组的类型必须为 `MultipartBody.Part[]`。RequestBody无法保存键名，只有 `MultipartBody.Part`才支持保存键值。
